#define WORKGROUP_SIZE 8*8
static const float threshold = 1e-3;

struct Cluster{
    float3 pMin;
    float _pad0; //对齐
    float3 pMax;
    float _pad1; //对齐
    uint triangleStart;
    uint triangleEnd;
    uint2 _pad2;
};

struct DrawIndirectArgs
{
    uint indexCount;
    uint instanceCount;
    uint firstIndex;
    uint vertexOffset;
    uint firstInstance;
};

// binding
[[vk::binding(0, 0)]]
StructuredBuffer<Cluster> inputData;
[[vk::binding(1, 0)]]
StructuredBuffer<uint> inTriangles;
[[vk::binding(2, 0)]]
RWStructuredBuffer<uint> outTriangles;
[[vk::binding(3, 0)]]
RWStructuredBuffer<DrawIndirectArgs> numVertices;
[[vk::binding(6, 0)]]
StructuredBuffer<float2> errorData;

[[vk::binding(5, 0)]]
Texture2D<float> lastHZB;
[[vk::binding(5, 0)]]
SamplerState hzbSampler;

[[vk::binding(4, 0)]]
cbuffer UBOMats:register(b0)
{
    float4x4 model;
    float4x4 lastView;
    float4x4 lastProj;
};

struct PushConstants
{
    int numClusters;
};

[[vk::push_constant]]
PushConstants pushConstants;

void getScreenAABB(Cluster cluster, inout float4 screenXY, inout float minZ)
{
    float4 pointArray[8];
    float4 pointMVPArray[8];

    float2 minXY = float2(1.0,1.0);
    float2 maxXY = float2(0.0, 0.0);

    float3 corners[8] = {
      float3(cluster.pMin.x, cluster.pMin.y, cluster.pMin.z),
      float3(cluster.pMin.x, cluster.pMin.y, cluster.pMax.z),
      float3(cluster.pMin.x, cluster.pMax.y, cluster.pMin.z),
      float3(cluster.pMin.x, cluster.pMax.y, cluster.pMax.z),
      float3(cluster.pMax.x, cluster.pMin.y, cluster.pMin.z),
      float3(cluster.pMax.x, cluster.pMin.y, cluster.pMax.z),
      float3(cluster.pMax.x, cluster.pMax.y, cluster.pMin.z),
        float3(cluster.pMax.x, cluster.pMax.y, cluster.pMax.z),
    };

    [unroll]
    for(int i = 0; i <8; i++)
    {
        pointArray[i] = float4(corners[i], 1.0);
        pointMVPArray[i] = mul(lastProj, mul(lastView, pointArray[i]));
        pointMVPArray[i].xyz /= pointMVPArray[i].w;
        pointMVPArray[i] = pointMVPArray[i]*0.5 + 0.5;

        minZ = min(minZ, pointMVPArray[i].z);
        minXY = min(minXY, pointMVPArray[i].xy);
        maxXY = max(maxXY, pointMVPArray[i].xy);
    }

    screenXY.xy = minXY;
    screenXY.zw = maxXY;
}

bool frustumCulling(float3 pos, float4x4 curView, float4x4 curProj)
{
    float4 hizPos = mul(curProj, mul(curView, float4(pos, 1.0)));
    if(hizPos.w == 0.0)
        return false;

    hizPos.xyz /= hizPos.w;
    return hizPos.x >= -1.1 && hizPos.x <= 1.1 && hizPos.y >= -1.1 && hizPos.y <= 1.1;  
}

[numthreads(WORKGROUP_SIZE, 1, 1)]
void main(uint3 dispatchThreadID: SV_DispatchThreadID)
{
    uint index = dispatchThreadID.x;
    if(index >= (uint)pushConstants.numClusters)
        return;
    
    bool culled = false;

    culled = culled || (errorData[index].y <= threshold || errorData[index].x >= threshold);

    if(culled == false)
    {
        uint totalVertices = (inputData[index].triangleEnd - inputData[index].triangleStart)*3;

        uint nIdx;
        InterlockedAdd(numVertices[index].instanceCount, totalVertices, nIdx);

        for(uint i = 0;i < totalVertices/3; i++)
        {
            uint srcIndex = inputData[index].triangleStart*3 + 3*i;
            uint outIndex = nIdx + 3*i;
            outTriangles[outIndex + 0] = inTriangles[srcIndex + 0];
            outTriangles[outIndex + 1] = inTriangles[srcIndex + 1];
            outTriangles[outIndex + 2] = inTriangles[srcIndex + 2];
        }
    }
}
