#version 450
// 支持64位整数的 基础64位整数支持
#extension GL_EXT_shader_image_int64 : enable
// buffer的64位原子操作
#extension GL_EXT_shader_atomic_int64 : enable
// image的64位原子write read操作
#extension GL_ARB_gpu_shader_int64 : enable

#define work_group_size 8
layout(local_size_x = work_group_size, local_size_y = work_group_size, local_size_z = 1) in;


layout(set = 0, binding = 0, r64ui) uniform u64image2D swDepthVisBuffer;

layout(std430, set = 0, binding = 1) buffer readonly NumVerticesSw
{
    uint indexCount;
}numVerticesSW;

layout(std430, set = 0, binding = 2) buffer writeonly SWDispatch
{
    uint x;
    uint y;
    uint z;
}swDispatch;

void main()
{
    uvec2 screenSize = imageSize(swDepthVisBuffer).xy;
    ivec2 index = ivec2(gl_GlobalInvocationID.xy);
    if(index.x == 0 && index.y == 0)
    {
        swDispatch.x = (numVerticesSW.indexCount/3 + 63)/64;
        swDispatch.y = 1;
        swDispatch.z = 1;
    }

    if(index.x >= screenSize.x || index.y >= screenSize.y)
        return;
    
    imageStore(swDepthVisBuffer, index, i64vec4(0x0L));
}
